"use client";

import type { ExamQuestion } from "@/lib/api";

type QuestionNavigatorProps = Readonly<{ questions: ExamQuestion[]; currentIndex: number; answers: Record<number, number>; onSelect: (index: number) => void }>;

export function QuestionNavigator({ questions, currentIndex, answers, onSelect }: QuestionNavigatorProps) {
  return <div className="mt-7 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-semibold text-slate-800">Question navigator</p><div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-xs font-medium text-slate-500"><span className="inline-flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-emerald-500" />Green = Answered</span><span className="inline-flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full border border-red-400 bg-red-50" />Red/Orange = Unanswered</span></div></div><div className="mt-4 grid grid-cols-5 gap-2 sm:grid-cols-10">{questions.map((item, index) => { const current = index === currentIndex; const answered = answers[item.id] !== undefined; return <button key={item.id} onClick={() => onSelect(index)} aria-label={`Go to question ${index + 1}${answered ? ", answered" : ", unanswered"}`} className={`relative h-10 rounded-lg text-sm font-bold transition ${current ? "bg-indigo-600 text-white ring-4 ring-indigo-100" : answered ? "bg-emerald-50 text-emerald-700 hover:bg-emerald-100" : "border border-red-300 bg-red-50 text-red-700 hover:bg-orange-50"}`}>{index + 1}{current && !answered && <span aria-label="Current question is unanswered" className="absolute -right-1 -top-1 grid h-4 w-4 place-items-center rounded-full bg-orange-500 text-[10px] font-black text-white ring-2 ring-white">!</span>}</button>; })}</div></div>;
}
