<?php
namespace Tests\Feature;
use App\Models\Question; use App\Models\User; use App\Services\AssessmentExamService; use Database\Seeders\QuestionSeeder; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class HardeningAndShuffleTest extends TestCase { use RefreshDatabase; private User $student; protected function setUp(): void { parent::setUp(); $this->seed(QuestionSeeder::class); $this->student=User::factory()->create(['role'=>'student']); }
public function test_shuffle_is_stable_persisted_balanced_and_safe(): void { $r=$this->actingAs($this->student,'sanctum')->postJson('/api/attempts')->assertCreated(); $id=$r->json('attempt.id'); $a=$r->json('attempt.questions'); $b=$this->actingAs($this->student,'sanctum')->getJson("/api/attempts/$id")->assertOk()->json('attempt.questions'); $this->assertSame($a,$b); $this->assertCount(10,$a); $this->assertCount(10,collect($a)->pluck('id')->unique()); foreach(range(1,5) as $l)$this->assertSame(2,collect($a)->where('level',$l)->count()); $this->assertDatabaseHas('attempt_answers',['attempt_id'=>$id,'position'=>1]); $r->assertJsonMissingPath('attempt.questions.0.correct_option')->assertJsonMissingPath('attempt.questions.0.points')->assertJsonMissingPath('attempt.questions.0.option_order'); }
public function test_shuffled_identifiers_grade_correctly_and_invalid_input_is_rejected(): void { $a=app(AssessmentExamService::class)->startAttempt($this->student); $shown=$this->actingAs($this->student,'sanctum')->getJson("/api/attempts/$a->id")->json('attempt.questions'); $answers=collect($shown)->map(fn($q)=>['question_id'=>$q['id'],'selected_option'=>Question::find($q['id'])->correct_option])->all(); $this->actingAs($this->student,'sanctum')->postJson("/api/attempts/$a->id/submit",['answers'=>$answers])->assertOk()->assertJsonPath('attempt.total_score',30)->assertJsonPath('attempt.level_name','Expert'); $b=app(AssessmentExamService::class)->startAttempt($this->student); $qid=$b->answers()->first()->question_id; $this->actingAs($this->student,'sanctum')->postJson("/api/attempts/$b->id/submit",['answers'=>[['question_id'=>9999,'selected_option'=>0]]])->assertUnprocessable(); $this->actingAs($this->student,'sanctum')->postJson("/api/attempts/$b->id/submit",['answers'=>[['question_id'=>$qid,'selected_option'=>0],['question_id'=>$qid,'selected_option'=>1]]])->assertUnprocessable(); }
public function test_ownership_and_uniform_errors(): void { $a=app(AssessmentExamService::class)->startAttempt($this->student); $other=User::factory()->create(['role'=>'student']); $this->actingAs($other,'sanctum')->getJson("/api/attempts/$a->id")->assertNotFound(); $this->actingAs($other,'sanctum')->patchJson("/api/attempts/$a->id/answers",['answers'=>[['question_id'=>1,'selected_option'=>0]]])->assertNotFound(); $this->actingAs($other,'sanctum')->postJson("/api/attempts/$a->id/submit",['answers'=>[]])->assertNotFound(); $this->app['auth']->forgetGuards(); $this->getJson('/api/attempts')->assertUnauthorized()->assertJsonStructure(['message','errors','code']); $this->actingAs($this->student,'sanctum')->getJson('/api/admin/questions')->assertForbidden()->assertJsonStructure(['message','errors','code']); }
    public function test_error_envelopes_without_throttle_exhaustion(): void { $this->app['auth']->forgetGuards(); $this->getJson('/api/no-route')->assertNotFound()->assertJsonStructure(['message','errors','code']); $this->getJson('/api/login')->assertMethodNotAllowed()->assertJsonStructure(['message','errors','code']); $this->postJson('/api/register',[])->assertUnprocessable()->assertJsonStructure(['message','errors','code','errors'=>['name','email','password']]); }
    public function test_login_limiter_returns_uniform_429(): void { foreach (range(1,10) as $_) $this->postJson('/api/login',['email'=>'same@example.com','password'=>'wrongpass'])->assertUnprocessable(); $this->postJson('/api/login',['email'=>'same@example.com','password'=>'wrongpass'])->assertStatus(429)->assertJsonStructure(['message','errors','code']); }
    public function test_register_limiter_returns_uniform_429(): void { foreach (range(1,10) as $i) $this->postJson('/api/register',['name'=>"User $i",'email'=>"rate$i@example.com",'password'=>'password123','password_confirmation'=>'password123'])->assertCreated(); $this->postJson('/api/register',['name'=>'Blocked','email'=>'blocked@example.com','password'=>'password123','password_confirmation'=>'password123'])->assertStatus(429)->assertJsonStructure(['message','errors','code']); }}
